### ISSUE TITLE
Je ne sais pas calculer Bêta

### ISSUE THREAD

**Issue by BaptisteUgo** [mathlorgues/math1sd1516#1]

**Comment by mathlorgues** [comment]
Bêta est la notation usuelle pour l'ordonnée du sommet d'une parabole. De quelle parabole il s'agit ?
Es-tu en train de faire un exercice ?

**Comment by BaptisteUgo** [comment]
oui l'exercice 1 de la séance du jeudi 3 septembre:

https://github.com/BaptisteUgo/BaptisteUgo/blob/master/20150903/Ex%201.odt

**Comment by mathlorgues** [comment]
fermeture de cette issue de démonstration.
