### ISSUE TITLE
Problème - Equation bicarrée

### ISSUE THREAD

**Issue by flavbleach** [mathlorgues/math1sd1516#10]
Bonjour,

Exercice 5 de ce document :http://www.xm1math.net/premiere_s/prem_s_chap1_exos.pdf
Je me trouve confronté à un problème : comment résoudre les équations à puissances supérieures à 2 ? (Dans ce cas ci une équation bicarrée sous forme x^4+x^2+c)

Merci d'avance pour votre aide.

**Comment by mathlorgues** [comment]
J'ai vu ta question. Je n'y réponds pas pour le moment. C'est une très bonne question.
