### ISSUE TITLE
Contrôle du 13/11

### ISSUE THREAD

**Issue by MathiasHauchard** [mathlorgues/math1sd1516#11]
bonjour, je voulais savoir dans quel cas nous servais 1/m ( mx+p)

**Comment by duccharly** [comment]
Et bien, prenons un exemple simple :

Soit d une droit d'équation 2x + 3 = y.
Donner un vecteur directeur de cette droite.

Réponse : Vecteur u de coordonnées (1;2)

**Comment by MathiasHauchard** [comment]
ahh et par exemple 6x+8=Y
vecteur directeur : (1;6) 
c'est bien ça ?

**Comment by duccharly** [comment]
c'est ça !

**Comment by MathiasHauchard** [comment]
merci !
