### ISSUE TITLE
Quel est l'intérêt de reconnaître une suite arithmétique ?

### ISSUE THREAD

**Issue by flavbleach** [mathlorgues/math1sd1516#12]
Bonjour,

Je semble ne pas avec encore saisi l'intérêt de reconnaitre une suite arithmétique.
En effet, pour moi pour le moment, ce terme est seulement défini par une simple formule : 

U(n+1) = U(n)+r

Et trouvé si la formule suivante résulte en un entier (i ici) : 

U(n+1) - U(n) = i

Merci !

**Comment by mathlorgues** [comment]
Ce que nous saurons (sur les suites arithmétiques) à la fin du cours sur les suites :

1. La définition de telles suites, à l'aide d'une formule de récurrence et d'un __premier terme__ (déjà vu).
2. La formule permettant de calculer n'importe quel terme quand on en connait 2 (ou 1 seul et la raison) (*déjà vu).
3. Des techniques (voire une formule) permettant de calculer une somme de termes consécutifs.

Ainsi, reconnaitre (à l'aide de 1.) qu'une suite est arithmétique permet d'appliquer le deuxième ou le troisième point. On peut trouver que cela est bien peu de choses. En effet, les suites arithmétiques sont des objets mathématiques assez simples. Elles constituent qu'une partie de ce cours. Plus généralement, les suites arithmétiques et géométriques sont l'occasion de se familiariser avec la notion de définition par récurrence qui se prolongera en classe de terminal par la technique de démonstration d'une proposition par récurrence.
