### ISSUE TITLE
AP

### ISSUE THREAD

**Issue by matthisgonon** [mathlorgues/math1sd1516#3]
@mathlorgues  @matthisA @camille83131 @dasilva-max @mathiashauchard @AmauryDeconinck @AntoineCarletto @HugoCogne

**Comment by AmauryDeconinck** [comment]
Bonjour.

**Comment by BeInTooo** [comment]
bonjou toi

**Comment by MathiasHauchard** [comment]
tu as fait une erreur c'est "bonjouR"

**Comment by dasilva-max** [comment]
coucou !! :)

**Comment by MathiasHauchard** [comment]
je te le signal

**Comment by dasilva-max** [comment]
nn c'est ses "bonjou" a lui tkt XD

**Comment by MatthisA** [comment]
"SignalE"

**Comment by AntoineCarletto** [comment]
Dur

**Comment by HugoCogne** [comment]
J ai le plus beau avatar

**Comment by HugoCogne** [comment]
fé pa leu bo tu neu meu koné pa wsh

**Comment by AmauryDeconinck** [comment]
Watch out, we got a badass over here!

**Comment by AntoineCarletto** [comment]
azy chersh pa lé noiz tu koné pa lé bay

**Comment by HugoCogne** [comment]
vin deu moillenne an frensé sa paille

**Comment by MathiasHauchard** [comment]
#Ok

**Comment by MatthisA** [comment]
#Rammus

**Comment by MathiasHauchard** [comment]
#c'estlarécré

**Comment by mathlorgues** [comment]
Fermeture de cette issue de test.
