### ISSUE TITLE
Exercice de math

### ISSUE THREAD

**Issue by HugoSiri** [mathlorgues/math1sd1516#7]

**Comment by HugoSiri** [comment]
Bonjour, qui pourrait me donner l'énoncé de l'exercice car je ne peux pas le faire je n'ai pas mon livre?
Merci

**Comment by AntoineCarletto** [comment]
Wesh, 
C'est l'exercice 54;
http://hpics.li/21823fe

**Comment by HugoSiri** [comment]
Merci

**Comment by mathlorgues** [comment]
Je ferme. Le problème ayant été résolu.
