### ISSUE TITLE
[Ex56p38] Forme grammaticale

### ISSUE THREAD

**Issue by flavbleach** [mathlorgues/math1sd1516#8]
Bonjour,

Voici la correction de l'exercice 56p38 du livre.

Afin que le trinôme possède en solution une racine double, il faut que b²-4ac=0.
Soit dans ce trinôme : b=6, c=1.
6²-(4*x)=0
4x=36
x=9

- La phrase de conclusion suivante est-elle grammaticalement correcte ?

Soit 9 solution unique pour le coefficient directeur a afin que le trinôme admette une racine double en solution.

Merci,

**Comment by mathlorgues** [comment]
1) Dans la première phrase, n'écris pas : "en solution"

On ne doit pas utiliser le mot solution sans expliciter de quoi l'objet est solution ou alors seulement quand le problème dont l'objet est solution est parfaitement évident. Par exemple dans le cas de la résolution d'une équation.

2) il faut et **il suffit** que b²-4ac=0.
En mathématiques 
- il faut
- il suffit
- il faut et il suffit

sont trois expressions qui ont un sens précis. Ici, admettre une racine double et avoir son discriminant nul sont deux assertions équivalentes.Cela signifie que les deux énoncés suivants sont vrais:

- Si le discriminant d'un trinôme est nul alors ce trinôme admet une racine double.
- Si le trinôme admet une racine double alors son discriminant est nul.

Ce que tu écris est juste mais tu perds une partie de l'articulation logique. Dans ces conditions pour répondre correctement à la question tu devrais à la fin vérifier que pour a=9 le trinôme admet bien une racine double. 

3) La variable de l'équation "discriminant égal à 0" est le paramêtre a. Il est déjà nommé. Il ne faut pas le changer en x, d'autant que x a déjà un autre sens, ici : c'est la variable du trinôme.

6²-(4*a)=0
4a=36
a=9

4) Dans le cas d'un trinôme a n'est pas appelé coefficient directeur mais coefficient dominant (pour dire de plus haut degré).

5) Soit est une expression que l'on utilise très souvent en mathématique 
- Pour introduire un nouvel objet mathématique. Exemple : Soit p le premier entier premier plus grand que 100.
- Pour réaliser une disjonction de cas. Exemple : Soit n est un entier pair, soit n est un entier impair.

Mieux vaut ne pas l'utiliser pour indiquer une reformulation ou une conclusion. Préférer les expressions "ou encore", "en définitive" et "ainsi".

Une fois que le problème est résolu, l'affirmation de conclusion n'a pas besoin comme dans la question d'utiliser le subjonctif.

6) A nouveau, ne pas utiliser solution dans la dernière phrase, pour les mêmes raisons qu'en 1).

Voici les corrections de rédaction que je préconise alors.

*Afin que le trinôme possède une racine double, il faut* **et il suffit** *que b²-4ac=0.*
*Or dans ce trinôme : b=6, c=1.
et les égalités suivantes sont équivalentes:*

*b²-4ac=0
6²-(4a)=0
4a=36
a=9*

*Ainsi, 9 est l'unique valeur de a pour laquelle le trinôme admet une racine double.*
